-- ============================================================================
-- Upside Tree Seed Product Catalog (30 Products across 10 Categories)
-- ============================================================================

-- 1. SEED COLLECTIONS
INSERT INTO public.collections (id, name_en, name_fa, slug, description_en, description_fa, story_en, story_fa, color_palette, status, featured, sort_order)
VALUES 
  (
    'a1111111-1111-1111-1111-111111111111',
    'Roots',
    'ریشه‌ها',
    'roots',
    'Symbols of ancient Iranian sovereignty, architecture, and enduring identity.',
    'نمادهای اقتدار، معماری و هویت پایدار ایران باستان.',
    'Rooted in ancient soil. Designed for modern presence.',
    'ریشه در خاک کهن، طراحی‌شده برای حضور امروز.',
    ARRAY['#1D4E89', '#B48635', '#F4EFE3'],
    'active',
    true,
    1
  ),
  (
    'a2222222-2222-2222-2222-222222222222',
    'Words',
    'واژه‌ها',
    'words',
    'Secular literature, cuneiform script, and classical poetry transformed into modern typography.',
    'ادبیات، خط میخی و اشعار کلاسیك در قالب تایپوگرافی مدرن.',
    'Words that carved freedom into stone long before the world had a name for it.',
    'واژه‌هایی که آزادی را بر سنگ نگاشتند.',
    ARRAY['#18231F', '#1D4E89', '#F4EFE3'],
    'active',
    true,
    2
  ),
  (
    'a3333333-3333-3333-3333-333333333333',
    'Rituals',
    'آیین‌ها',
    'rituals',
    'Pre-Islamic seasonal celebrations of Nowruz, Yalda, and eternal flame traditions.',
    'جشن‌های کهن ایرانی، نوروز، شب یلدا و آیین‌های مهر و آتش.',
    'Centuries of light celebrated anew at every solar renewal.',
    'قرن‌ها روشنایی در هر رستاخیز خورشید.',
    ARRAY['#8C2F39', '#B48635', '#1F8A8A'],
    'active',
    true,
    3
  ),
  (
    'a4444444-4444-4444-4444-444444444444',
    'Made by Hand',
    'دست‌سازها',
    'made-by-hand',
    'Artisanal collaborations with master Iranian ceramicists, weavers, and metalworkers.',
    'همکاری با هنرمندان و استادکاران سفال، بافت و فلزکاری.',
    'Crafted by human hands to honor timeless geometry.',
    'ساخته‌شده با دست انسان برای بزرگداشت هندسه جاودان.',
    ARRAY['#B6653B', '#697A4D', '#F4EFE3'],
    'active',
    false,
    4
  ),
  (
    'a5555555-5555-5555-5555-555555555555',
    'Limited Stories',
    'قصه‌های محدود',
    'limited-stories',
    'Numbered limited edition heritage objects for collectors and cultural curators.',
    'آثار محدود و شماره‌گذاری‌شده برای کلکسیونرها و حامیان فرهنگ.',
    'Rare narratives produced in small, numbered batches.',
    'روایت‌های کمیاب در نسخه‌های محدود و شماره‌گذاری‌شده.',
    ARRAY['#B48635', '#18231F', '#8C2F39'],
    'active',
    true,
    5
  ),
  (
    'a6666666-6666-6666-6666-666666666666',
    'T-shirts',
    'تی‌شرت‌ها',
    't-shirts',
    'Everyday wearable art infused with ancient Persian motifs.',
    'هنر پوشیدنی روزمره، درآمیخته با نقوش باستانی ایران.',
    'Everyday wearable art infused with ancient Persian motifs.',
    'هنر پوشیدنی روزمره، درآمیخته با نقوش باستانی ایران.',
    ARRAY['#1D4E89', '#F4EFE3'],
    'active',
    false,
    6
  ),
  (
    'a7777777-7777-7777-7777-777777777777',
    'Sweatshirts',
    'سوییشرت‌ها',
    'sweatshirts',
    'Warm, premium layers wrapped in the elegance of Persian heritage.',
    'لایه‌های گرم و پریمیوم در حصار شکوه میراث ایرانی.',
    'Warm, premium layers wrapped in the elegance of Persian heritage.',
    'لایه‌های گرم و پریمیوم در حصار شکوه میراث ایرانی.',
    ARRAY['#8C2F39', '#F4EFE3'],
    'active',
    false,
    7
  ),
  (
    'a8888888-8888-8888-8888-888888888888',
    'Mugs',
    'ماگ‌ها',
    'mugs',
    'Ceramic vessels bringing the warmth of Persian hospitality to your daily chai.',
    'ظروف سرامیکی برای آوردن گرمای مهمان‌نوازی ایرانی به چای روزانه شما.',
    'Ceramic vessels bringing the warmth of Persian hospitality to your daily chai.',
    'ظروف سرامیکی برای آوردن گرمای مهمان‌نوازی ایرانی به چای روزانه شما.',
    ARRAY['#B48635', '#F4EFE3'],
    'active',
    true,
    8
  ),
  (
    'a9999999-9999-9999-9999-999999999999',
    'Hoodies',
    'هودی‌ها',
    'hoodies',
    'Modern comfort meets timeless calligraphy and geometric perfection.',
    'راحتی مدرن در کنار کمال هندسی و خطاطی جاودانه.',
    'Modern comfort meets timeless calligraphy and geometric perfection.',
    'راحتی مدرن در کنار کمال هندسی و خطاطی جاودانه.',
    ARRAY['#1F8A8A', '#F4EFE3'],
    'active',
    false,
    9
  ),
  (
    'a0000000-0000-0000-0000-000000000000',
    'Kids Clothing',
    'لباس کودک',
    'kids-clothing',
    'Passing down the stories of Shahnameh to the next generation.',
    'انتقال داستان‌های شاهنامه به نسل آینده.',
    'Passing down the stories of Shahnameh to the next generation.',
    'انتقال داستان‌های شاهنامه به نسل آینده.',
    ARRAY['#1D4E89', '#F4EFE3'],
    'active',
    false,
    10
  ),
  (
    'b1111111-1111-1111-1111-111111111111',
    'Stickers',
    'استیکرها',
    'stickers',
    'Small pieces of art to carry Persian culture wherever you go.',
    'قطعات کوچک هنری برای همراه داشتن فرهنگ ایرانی در هر جا.',
    'Small pieces of art to carry Persian culture wherever you go.',
    'قطعات کوچک هنری برای همراه داشتن فرهنگ ایرانی در هر جا.',
    ARRAY['#18231F', '#F4EFE3'],
    'active',
    false,
    11
  ),
  (
    'b2222222-2222-2222-2222-222222222222',
    'Phone Cases',
    'قاب گوشی',
    'phone-cases',
    'Protect your technology with the resilience of ancient architecture.',
    'محافظت از تکنولوژی با اصالت معماری باستانی.',
    'Protect your technology with the resilience of ancient architecture.',
    'محافظت از تکنولوژی با اصالت معماری باستانی.',
    ARRAY['#B48635', '#F4EFE3'],
    'active',
    false,
    12
  ),
  (
    'b3333333-3333-3333-3333-333333333333',
    'Posters',
    'پوسترها',
    'posters',
    'Turn your walls into a gallery of Iranian history and poetry.',
    'دیوارهای خود را به گالری تاریخ و شعر ایران تبدیل کنید.',
    'Turn your walls into a gallery of Iranian history and poetry.',
    'دیوارهای خود را به گالری تاریخ و شعر ایران تبدیل کنید.',
    ARRAY['#8C2F39', '#F4EFE3'],
    'active',
    true,
    13
  ),
  (
    'b4444444-4444-4444-4444-444444444444',
    'Candles',
    'شمع‌ها',
    'candles',
    'Illuminate your space with the glowing aromas of a Persian garden.',
    'فضای خود را با رایحه درخشان یک باغ ایرانی روشن کنید.',
    'Illuminate your space with the glowing aromas of a Persian garden.',
    'فضای خود را با رایحه درخشان یک باغ ایرانی روشن کنید.',
    ARRAY['#1F8A8A', '#F4EFE3'],
    'active',
    false,
    14
  ),
  (
    'b5555555-5555-5555-5555-555555555555',
    'Bags',
    'کیف‌ها',
    'bags',
    'Carry your world in bags woven with the spirit of the Silk Road.',
    'دنیای خود را در کیف‌هایی با روح جاده ابریشم حمل کنید.',
    'Carry your world in bags woven with the spirit of the Silk Road.',
    'دنیای خود را در کیف‌هایی با روح جاده ابریشم حمل کنید.',
    ARRAY['#1D4E89', '#F4EFE3'],
    'active',
    false,
    15
  )
,
(
  'p9900000-0000-0000-0000-000000000001',
  'rustic-ceramic-candle-holder-ut3507-1',
  'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Rustic Ceramic Candle Holder Set',
  'ست شمعدان سرامیکی روستیک',
  'A beautiful rustic candle holder setup with three thin metal candle holders and one large ceramic base, bringing warmth to any space.',
  'ست شمعدان روستیک زیبا با سه پایه فلزی ظریف و یک پایه سرامیکی بزرگ، گرمابخش هر فضا.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'Carefully crafted item.',
  'محصولی با ظرافت و دقت بالا.',
  85, 21.25, 'CAD', 'UT3507-1', true, 10,
  '/images/products/UT3507-1.jpg',
  ARRAY['/images/products/UT3507-1.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000000002',
  'sculptural-face-candle-holder-ut3506-1',
  'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Sculptural Face Candle Holder',
  'شمعدان مجسمه‌ای طرح چهره',
  'Artistic candle holder featuring intricately patterned structures and faces, a perfect centerpiece.',
  'شمعدان هنری با ساختارهای طرح‌دار پیچیده و چهره، یک مرکز توجه بی‌نظیر.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'Carefully crafted item.',
  'محصولی با ظرافت و دقت بالا.',
  120, 30, 'CAD', 'UT3506-1', true, 5,
  '/images/products/UT3506-1.jpg',
  ARRAY['/images/products/UT3506-1.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000000003',
  'modern-metal-portrait-ut3521-1',
  'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Modern Metal Portrait Artwork',
  'اثر هنری پرتره فلزی مدرن',
  'A striking modern framed metal artwork depicting a minimalist portrait, perfect for industrial or contemporary spaces.',
  'اثر هنری قاب‌دار فلزی مدرن و چشم‌گیر که پرتره‌ای مینیمال را به تصویر می‌کشد، ایده‌آل برای فضاهای صنعتی یا معاصر.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'Carefully crafted item.',
  'محصولی با ظرافت و دقت بالا.',
  250, 62.5, 'CAD', 'UT3521-1', true, 3,
  '/images/products/UT3521-1.jpg',
  ARRAY['/images/products/UT3521-1.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000000004',
  'ancient-stylized-animal-figurines-ut3505-1',
  'active', 'public', 'physical', 'e2222222-2222-2222-2222-222222222222',
  'Ancient Stylized Animal Figurines',
  'مجسمه‌های حیوانی استایل باستانی',
  'Set of two ancient-style metallic animal figurines featuring elaborate horns, echoing ancient Persian artistry.',
  'ست دو عددی مجسمه‌های حیوانی فلزی با استایل باستانی و شاخ‌های پرکار، یادآور هنر ایران باستان.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'Carefully crafted item.',
  'محصولی با ظرافت و دقت بالا.',
  180, 45, 'CAD', 'UT3505-1', true, 7,
  '/images/products/UT3505-1.jpg',
  ARRAY['/images/products/UT3505-1.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000000005',
  'golden-persian-calligraphy-art-ut3526-1',
  'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Golden Persian Calligraphy Art',
  'تابلو کالیگرافی طلایی ایرانی',
  'Elegant framed golden typography artwork on a dark background, adding a touch of classic Persian poetry to your walls.',
  'اثر هنری تایپوگرافی طلایی قاب‌دار روی پس‌زمینه تیره، برای افزودن حسی از شعر کلاسیک ایرانی به دیوارهای شما.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'Carefully crafted item.',
  'محصولی با ظرافت و دقت بالا.',
  210, 52.5, 'CAD', 'UT3526-1', true, 4,
  '/images/products/UT3526-1.jpg',
  ARRAY['/images/products/UT3526-1.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
)
,
(
  'p9900000-0000-0000-0000-000000002001',
  'lion-and-sun-t-shirts',
  'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Lion and Sun Emblem T Shirts',
  'محصول شیر و خورشید - T Shirts',
  'A premium t shirts featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (T Shirts) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-T-S-2001', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002002',
  'lion-and-sun-sweatshirts',
  'active', 'public', 'physical', 'a5555555-5555-5555-5555-555555555555',
  'Lion and Sun Emblem Sweatshirts',
  'محصول شیر و خورشید - Sweatshirts',
  'A premium sweatshirts featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Sweatshirts) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-SWE-2002', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002003',
  'lion-and-sun-mugs',
  'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Lion and Sun Emblem Mugs',
  'محصول شیر و خورشید - Mugs',
  'A premium mugs featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Mugs) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-MUG-2003', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002004',
  'lion-and-sun-hoodies',
  'active', 'public', 'physical', 'a7777777-7777-7777-7777-777777777777',
  'Lion and Sun Emblem Hoodies',
  'محصول شیر و خورشید - Hoodies',
  'A premium hoodies featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Hoodies) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-HOO-2004', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002005',
  'lion-and-sun-kids-clothing',
  'active', 'public', 'physical', 'a8888888-8888-8888-8888-888888888888',
  'Lion and Sun Emblem Kids Clothing',
  'محصول شیر و خورشید - Kids Clothing',
  'A premium kids clothing featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Kids Clothing) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-KID-2005', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002006',
  'lion-and-sun-stickers',
  'active', 'public', 'physical', 'a9999999-9999-9999-9999-999999999999',
  'Lion and Sun Emblem Stickers',
  'محصول شیر و خورشید - Stickers',
  'A premium stickers featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Stickers) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-STI-2006', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002007',
  'lion-and-sun-phone-cases',
  'active', 'public', 'physical', 'b1111111-1111-1111-1111-111111111111',
  'Lion and Sun Emblem Phone Cases',
  'محصول شیر و خورشید - Phone Cases',
  'A premium phone cases featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Phone Cases) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-PHO-2007', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002008',
  'lion-and-sun-posters',
  'active', 'public', 'physical', 'b2222222-2222-2222-2222-222222222222',
  'Lion and Sun Emblem Posters',
  'محصول شیر و خورشید - Posters',
  'A premium posters featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Posters) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-POS-2008', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002009',
  'lion-and-sun-candles',
  'active', 'public', 'physical', 'b3333333-3333-3333-3333-333333333333',
  'Lion and Sun Emblem Candles',
  'محصول شیر و خورشید - Candles',
  'A premium candles featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Candles) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-CAN-2009', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002010',
  'lion-and-sun-bags',
  'active', 'public', 'physical', 'b4444444-4444-4444-4444-444444444444',
  'Lion and Sun Emblem Bags',
  'محصول شیر و خورشید - Bags',
  'A premium bags featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Bags) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-BAG-2010', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002011',
  'lion-and-sun-roots',
  'active', 'public', 'physical', 'a1111111-1111-1111-1111-111111111111',
  'Lion and Sun Emblem Roots',
  'محصول شیر و خورشید - Roots',
  'A premium roots featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Roots) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-ROO-2011', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002012',
  'lion-and-sun-words',
  'active', 'public', 'physical', 'a2222222-2222-2222-2222-222222222222',
  'Lion and Sun Emblem Words',
  'محصول شیر و خورشید - Words',
  'A premium words featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Words) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-WOR-2012', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002013',
  'lion-and-sun-rituals',
  'active', 'public', 'physical', 'a3333333-3333-3333-3333-333333333333',
  'Lion and Sun Emblem Rituals',
  'محصول شیر و خورشید - Rituals',
  'A premium rituals featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Rituals) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-RIT-2013', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002014',
  'lion-and-sun-made-by-hand',
  'active', 'public', 'physical', 'e2222222-2222-2222-2222-222222222222',
  'Lion and Sun Emblem Made By Hand',
  'محصول شیر و خورشید - Made By Hand',
  'A premium made by hand featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Made By Hand) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-MAD-2014', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
),
(
  'p9900000-0000-0000-0000-000000002015',
  'lion-and-sun-limited-stories',
  'active', 'public', 'physical', 'e3333333-3333-3333-3333-333333333333',
  'Lion and Sun Emblem Limited Stories',
  'محصول شیر و خورشید - Limited Stories',
  'A premium limited stories featuring the timeless Persian Lion and Sun emblem, representing strength, light, and enduring heritage.',
  'این محصول (Limited Stories) مزین به نشان تاریخی شیر و خورشید، نماد قدرت، نور و میراث اصیل ایرانی است.',
  'Premium material',
  'مواد اولیه پریمیوم',
  'A classic tribute to Persian heritage.',
  'ادای احترامی کلاسیک به میراث ایرانی.',
  45, 11.25, 'CAD', 'LS-LIM-2015', true, 20,
  '/images/placeholder.jpg',
  ARRAY['/images/placeholder.jpg'],
  '{"has_story": true, "fits_collection": true, "persian_reviewed": true}'::jsonb,
  now()
)
ON CONFLICT (id) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_fa = EXCLUDED.name_fa,
  slug = EXCLUDED.slug;

-- 2. SEED PRODUCTS (75 PRODUCTS Across 15 Categories)
INSERT INTO public.products (
  id, slug, status, visibility, product_type, collection_id,
  name_en, name_fa,
  desc_emotional_en, desc_emotional_fa,
  desc_functional_en, desc_functional_fa,
  desc_story_en, desc_story_fa,
  price, cost_price, currency, sku, manage_stock, stock_quantity,
  featured_image_url, gallery_urls,
  brand_gate, published_at
) VALUES
(
  'dfc33250-a921-4c2c-94ea-aedd46a5de5d', 'roots-item-1', 'active', 'public', 'physical', 'a1111111-1111-1111-1111-111111111111',
  'Premium ROOTS No.1', 'محصول پریمیوم دسته‌بندی roots شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-ROOTS-01', false, 0,
  '/images/products/lion-and-sun-geometric-tee-mockup.png', ARRAY['/images/products/lion-and-sun-geometric-tee-mockup.png'],
  false, NOW()
),
(
  '406e0a1f-b758-4e1c-9831-c9da568974b6', 'roots-item-2', 'active', 'public', 'physical', 'a1111111-1111-1111-1111-111111111111',
  'Classic ROOTS No.2', 'محصول کلاسیک دسته‌بندی roots شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-ROOTS-02', false, 0,
  '/images/products/lion-and-sun-geometric-tee-mockup.png', ARRAY['/images/products/lion-and-sun-geometric-tee-mockup.png'],
  false, NOW()
),
(
  '5ad81158-e6c8-49bc-9c40-49347dde8403', 'roots-item-3', 'active', 'public', 'physical', 'a1111111-1111-1111-1111-111111111111',
  'Heritage ROOTS No.3', 'محصول میراث دسته‌بندی roots شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-ROOTS-03', false, 0,
  '/images/products/lion-and-sun-geometric-tee-mockup.png', ARRAY['/images/products/lion-and-sun-geometric-tee-mockup.png'],
  false, NOW()
),
(
  'eb671d4f-6e46-4539-b58e-6647f3243c64', 'roots-item-4', 'active', 'public', 'physical', 'a1111111-1111-1111-1111-111111111111',
  'Modern ROOTS No.4', 'محصول مدرن دسته‌بندی roots شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-ROOTS-04', false, 0,
  '/images/products/lion-and-sun-geometric-tee-mockup.png', ARRAY['/images/products/lion-and-sun-geometric-tee-mockup.png'],
  false, NOW()
),
(
  '620f1ff9-0e4b-4569-91fe-7cc7b4af0029', 'roots-item-5', 'active', 'public', 'physical', 'a1111111-1111-1111-1111-111111111111',
  'Artisanal ROOTS No.5', 'محصول دست‌ساز دسته‌بندی roots شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-ROOTS-05', false, 0,
  '/images/products/lion-and-sun-geometric-tee-mockup.png', ARRAY['/images/products/lion-and-sun-geometric-tee-mockup.png'],
  false, NOW()
),
(
  '20fbd927-ccea-46d6-8710-ef2962bf93b3', 'words-item-1', 'active', 'public', 'physical', 'a2222222-2222-2222-2222-222222222222',
  'Premium WORDS No.1', 'محصول پریمیوم دسته‌بندی words شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-WORDS-06', false, 0,
  '/images/products/cyrus-cuneiform-charter-tee-mockup.png', ARRAY['/images/products/cyrus-cuneiform-charter-tee-mockup.png'],
  false, NOW()
),
(
  'df6b086a-6a58-4448-bb75-97019d921d3b', 'words-item-2', 'active', 'public', 'physical', 'a2222222-2222-2222-2222-222222222222',
  'Classic WORDS No.2', 'محصول کلاسیک دسته‌بندی words شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-WORDS-07', false, 0,
  '/images/products/cyrus-cuneiform-charter-tee-mockup.png', ARRAY['/images/products/cyrus-cuneiform-charter-tee-mockup.png'],
  false, NOW()
),
(
  '4e3da476-cf42-4d57-9876-ebe0629210ac', 'words-item-3', 'active', 'public', 'physical', 'a2222222-2222-2222-2222-222222222222',
  'Heritage WORDS No.3', 'محصول میراث دسته‌بندی words شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-WORDS-08', false, 0,
  '/images/products/cyrus-cuneiform-charter-tee-mockup.png', ARRAY['/images/products/cyrus-cuneiform-charter-tee-mockup.png'],
  false, NOW()
),
(
  '640d51ab-8a60-4818-bd27-e22a43d71d1a', 'words-item-4', 'active', 'public', 'physical', 'a2222222-2222-2222-2222-222222222222',
  'Modern WORDS No.4', 'محصول مدرن دسته‌بندی words شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-WORDS-09', false, 0,
  '/images/products/cyrus-cuneiform-charter-tee-mockup.png', ARRAY['/images/products/cyrus-cuneiform-charter-tee-mockup.png'],
  false, NOW()
),
(
  '339e9ef6-2c50-4fcb-88ff-5aa8a9830d60', 'words-item-5', 'active', 'public', 'physical', 'a2222222-2222-2222-2222-222222222222',
  'Artisanal WORDS No.5', 'محصول دست‌ساز دسته‌بندی words شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-WORDS-10', false, 0,
  '/images/products/cyrus-cuneiform-charter-tee-mockup.png', ARRAY['/images/products/cyrus-cuneiform-charter-tee-mockup.png'],
  false, NOW()
),
(
  'fc26fbff-26ed-4075-898d-eb0a9714e08f', 'rituals-item-1', 'active', 'public', 'physical', 'a3333333-3333-3333-3333-333333333333',
  'Premium RITUALS No.1', 'محصول پریمیوم دسته‌بندی rituals شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-RITUALS-11', false, 0,
  '/images/products/yalda-night-ceremony-mug-mockup.png', ARRAY['/images/products/yalda-night-ceremony-mug-mockup.png'],
  false, NOW()
),
(
  '36b6e132-8f2d-42f3-a2bc-1716f800d8cd', 'rituals-item-2', 'active', 'public', 'physical', 'a3333333-3333-3333-3333-333333333333',
  'Classic RITUALS No.2', 'محصول کلاسیک دسته‌بندی rituals شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-RITUALS-12', false, 0,
  '/images/products/yalda-night-ceremony-mug-mockup.png', ARRAY['/images/products/yalda-night-ceremony-mug-mockup.png'],
  false, NOW()
),
(
  '8a18a327-2a1b-4247-9837-d8a4e67aa388', 'rituals-item-3', 'active', 'public', 'physical', 'a3333333-3333-3333-3333-333333333333',
  'Heritage RITUALS No.3', 'محصول میراث دسته‌بندی rituals شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-RITUALS-13', false, 0,
  '/images/products/yalda-night-ceremony-mug-mockup.png', ARRAY['/images/products/yalda-night-ceremony-mug-mockup.png'],
  false, NOW()
),
(
  '4f22047f-428a-41a4-9693-bf9b0fe701db', 'rituals-item-4', 'active', 'public', 'physical', 'a3333333-3333-3333-3333-333333333333',
  'Modern RITUALS No.4', 'محصول مدرن دسته‌بندی rituals شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-RITUALS-14', false, 0,
  '/images/products/yalda-night-ceremony-mug-mockup.png', ARRAY['/images/products/yalda-night-ceremony-mug-mockup.png'],
  false, NOW()
),
(
  '3d6b3439-32cc-4ae4-a1a8-73574d39a34c', 'rituals-item-5', 'active', 'public', 'physical', 'a3333333-3333-3333-3333-333333333333',
  'Artisanal RITUALS No.5', 'محصول دست‌ساز دسته‌بندی rituals شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-RITUALS-15', false, 0,
  '/images/products/yalda-night-ceremony-mug-mockup.png', ARRAY['/images/products/yalda-night-ceremony-mug-mockup.png'],
  false, NOW()
),
(
  '4556d04f-f8be-4054-9b43-38b8b1789394', 'made-by-hand-item-1', 'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Premium MADE BY-HAND No.1', 'محصول پریمیوم دسته‌بندی made-by-hand شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-MADE-BY-HAND-16', false, 0,
  '/images/products/handmade-ceramic-bowl.png', ARRAY['/images/products/handmade-ceramic-bowl.png'],
  false, NOW()
),
(
  '6cf18892-900f-4205-ae7b-4743cc7bbb1e', 'made-by-hand-item-2', 'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Classic MADE BY-HAND No.2', 'محصول کلاسیک دسته‌بندی made-by-hand شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-MADE-BY-HAND-17', false, 0,
  '/images/products/handmade-ceramic-bowl.png', ARRAY['/images/products/handmade-ceramic-bowl.png'],
  false, NOW()
),
(
  '7abd87ea-dfe9-484b-b282-ec2ff778927e', 'made-by-hand-item-3', 'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Heritage MADE BY-HAND No.3', 'محصول میراث دسته‌بندی made-by-hand شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-MADE-BY-HAND-18', false, 0,
  '/images/products/handmade-ceramic-bowl.png', ARRAY['/images/products/handmade-ceramic-bowl.png'],
  false, NOW()
),
(
  '7c10e402-09ea-4eeb-aa2e-1249809ca3cd', 'made-by-hand-item-4', 'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Modern MADE BY-HAND No.4', 'محصول مدرن دسته‌بندی made-by-hand شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-MADE-BY-HAND-19', false, 0,
  '/images/products/handmade-ceramic-bowl.png', ARRAY['/images/products/handmade-ceramic-bowl.png'],
  false, NOW()
),
(
  '99bbebca-dc39-477d-92be-9602a6d8b115', 'made-by-hand-item-5', 'active', 'public', 'physical', 'a4444444-4444-4444-4444-444444444444',
  'Artisanal MADE BY-HAND No.5', 'محصول دست‌ساز دسته‌بندی made-by-hand شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-MADE-BY-HAND-20', false, 0,
  '/images/products/handmade-ceramic-bowl.png', ARRAY['/images/products/handmade-ceramic-bowl.png'],
  false, NOW()
),
(
  'b413bdfd-75df-4c4d-8a81-9a47847a937a', 'limited-stories-item-1', 'active', 'public', 'physical', 'a5555555-5555-5555-5555-555555555555',
  'Premium LIMITED STORIES No.1', 'محصول پریمیوم دسته‌بندی limited-stories شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-LIMITED-STORIES-21', false, 0,
  '/images/products/limited-story-print.png', ARRAY['/images/products/limited-story-print.png'],
  false, NOW()
),
(
  'c9734997-abe5-4abe-b454-d6d7a03620c2', 'limited-stories-item-2', 'active', 'public', 'physical', 'a5555555-5555-5555-5555-555555555555',
  'Classic LIMITED STORIES No.2', 'محصول کلاسیک دسته‌بندی limited-stories شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-LIMITED-STORIES-22', false, 0,
  '/images/products/limited-story-print.png', ARRAY['/images/products/limited-story-print.png'],
  false, NOW()
),
(
  'dc2a4191-eaa0-44f3-8c50-1fcc4d30b719', 'limited-stories-item-3', 'active', 'public', 'physical', 'a5555555-5555-5555-5555-555555555555',
  'Heritage LIMITED STORIES No.3', 'محصول میراث دسته‌بندی limited-stories شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-LIMITED-STORIES-23', false, 0,
  '/images/products/limited-story-print.png', ARRAY['/images/products/limited-story-print.png'],
  false, NOW()
),
(
  '2bf1e3dd-da21-48a0-b4a6-0f1ba26a41cd', 'limited-stories-item-4', 'active', 'public', 'physical', 'a5555555-5555-5555-5555-555555555555',
  'Modern LIMITED STORIES No.4', 'محصول مدرن دسته‌بندی limited-stories شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-LIMITED-STORIES-24', false, 0,
  '/images/products/limited-story-print.png', ARRAY['/images/products/limited-story-print.png'],
  false, NOW()
),
(
  'e056f6ff-b649-421d-98be-cab16254827f', 'limited-stories-item-5', 'active', 'public', 'physical', 'a5555555-5555-5555-5555-555555555555',
  'Artisanal LIMITED STORIES No.5', 'محصول دست‌ساز دسته‌بندی limited-stories شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-LIMITED-STORIES-25', false, 0,
  '/images/products/limited-story-print.png', ARRAY['/images/products/limited-story-print.png'],
  false, NOW()
),
(
  'a9a54f17-08a7-4159-89df-ef6dfb7c8fe6', 't-shirts-item-1', 'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Premium T SHIRTS No.1', 'محصول پریمیوم دسته‌بندی t-shirts شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-T-SHIRTS-26', false, 0,
  '/images/category-tshirts.png', ARRAY['/images/category-tshirts.png'],
  false, NOW()
),
(
  '8c1e28d9-d43c-4821-9a00-275cdc2cf11d', 't-shirts-item-2', 'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Classic T SHIRTS No.2', 'محصول کلاسیک دسته‌بندی t-shirts شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-T-SHIRTS-27', false, 0,
  '/images/category-tshirts.png', ARRAY['/images/category-tshirts.png'],
  false, NOW()
),
(
  'c57bd8db-5d33-4fb4-9126-ef75bdf13b83', 't-shirts-item-3', 'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Heritage T SHIRTS No.3', 'محصول میراث دسته‌بندی t-shirts شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-T-SHIRTS-28', false, 0,
  '/images/category-tshirts.png', ARRAY['/images/category-tshirts.png'],
  false, NOW()
),
(
  '4ee20bee-5128-4eb1-9cea-1df7c666a257', 't-shirts-item-4', 'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Modern T SHIRTS No.4', 'محصول مدرن دسته‌بندی t-shirts شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-T-SHIRTS-29', false, 0,
  '/images/category-tshirts.png', ARRAY['/images/category-tshirts.png'],
  false, NOW()
),
(
  '1b7a6997-4eba-403c-a0de-5f5cb7adfe86', 't-shirts-item-5', 'active', 'public', 'physical', 'a6666666-6666-6666-6666-666666666666',
  'Artisanal T SHIRTS No.5', 'محصول دست‌ساز دسته‌بندی t-shirts شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-T-SHIRTS-30', false, 0,
  '/images/category-tshirts.png', ARRAY['/images/category-tshirts.png'],
  false, NOW()
),
(
  '44f777be-d22a-439e-b225-264b27de1623', 'sweatshirts-item-1', 'active', 'public', 'physical', 'a7777777-7777-7777-7777-777777777777',
  'Premium SWEATSHIRTS No.1', 'محصول پریمیوم دسته‌بندی sweatshirts شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-SWEATSHIRTS-31', false, 0,
  '/images/category-sweatshirt.png', ARRAY['/images/category-sweatshirt.png'],
  false, NOW()
),
(
  '5ef9809b-1ad2-44ea-87aa-094185795f97', 'sweatshirts-item-2', 'active', 'public', 'physical', 'a7777777-7777-7777-7777-777777777777',
  'Classic SWEATSHIRTS No.2', 'محصول کلاسیک دسته‌بندی sweatshirts شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-SWEATSHIRTS-32', false, 0,
  '/images/category-sweatshirt.png', ARRAY['/images/category-sweatshirt.png'],
  false, NOW()
),
(
  'b36f18c7-f27f-4e73-af54-bdba8cb30baa', 'sweatshirts-item-3', 'active', 'public', 'physical', 'a7777777-7777-7777-7777-777777777777',
  'Heritage SWEATSHIRTS No.3', 'محصول میراث دسته‌بندی sweatshirts شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-SWEATSHIRTS-33', false, 0,
  '/images/category-sweatshirt.png', ARRAY['/images/category-sweatshirt.png'],
  false, NOW()
),
(
  '2d234074-d33e-4d8c-b7a6-bce5af2fbe69', 'sweatshirts-item-4', 'active', 'public', 'physical', 'a7777777-7777-7777-7777-777777777777',
  'Modern SWEATSHIRTS No.4', 'محصول مدرن دسته‌بندی sweatshirts شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-SWEATSHIRTS-34', false, 0,
  '/images/category-sweatshirt.png', ARRAY['/images/category-sweatshirt.png'],
  false, NOW()
),
(
  '9c46e306-cfad-473d-a9f8-02f42c1037e4', 'sweatshirts-item-5', 'active', 'public', 'physical', 'a7777777-7777-7777-7777-777777777777',
  'Artisanal SWEATSHIRTS No.5', 'محصول دست‌ساز دسته‌بندی sweatshirts شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-SWEATSHIRTS-35', false, 0,
  '/images/category-sweatshirt.png', ARRAY['/images/category-sweatshirt.png'],
  false, NOW()
),
(
  '7536e98c-d5d9-4336-9d7b-575cfc5a086e', 'mugs-item-1', 'active', 'public', 'physical', 'a8888888-8888-8888-8888-888888888888',
  'Premium MUGS No.1', 'محصول پریمیوم دسته‌بندی mugs شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-MUGS-36', false, 0,
  '/images/category-mugs.png', ARRAY['/images/category-mugs.png'],
  false, NOW()
),
(
  '9d1875fd-c8c4-426d-9484-0f3f6e14ed7a', 'mugs-item-2', 'active', 'public', 'physical', 'a8888888-8888-8888-8888-888888888888',
  'Classic MUGS No.2', 'محصول کلاسیک دسته‌بندی mugs شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-MUGS-37', false, 0,
  '/images/category-mugs.png', ARRAY['/images/category-mugs.png'],
  false, NOW()
),
(
  '79c100d7-2989-4408-a596-00c3546b8819', 'mugs-item-3', 'active', 'public', 'physical', 'a8888888-8888-8888-8888-888888888888',
  'Heritage MUGS No.3', 'محصول میراث دسته‌بندی mugs شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-MUGS-38', false, 0,
  '/images/category-mugs.png', ARRAY['/images/category-mugs.png'],
  false, NOW()
),
(
  '6aa6da47-cec1-4bc1-81d5-05ada12a5654', 'mugs-item-4', 'active', 'public', 'physical', 'a8888888-8888-8888-8888-888888888888',
  'Modern MUGS No.4', 'محصول مدرن دسته‌بندی mugs شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-MUGS-39', false, 0,
  '/images/category-mugs.png', ARRAY['/images/category-mugs.png'],
  false, NOW()
),
(
  '8096d64f-15a7-42b8-9e73-8401bd9184aa', 'mugs-item-5', 'active', 'public', 'physical', 'a8888888-8888-8888-8888-888888888888',
  'Artisanal MUGS No.5', 'محصول دست‌ساز دسته‌بندی mugs شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-MUGS-40', false, 0,
  '/images/category-mugs.png', ARRAY['/images/category-mugs.png'],
  false, NOW()
),
(
  '16899303-d7b0-4a2b-be9b-60ae9a2cec57', 'hoodies-item-1', 'active', 'public', 'physical', 'a9999999-9999-9999-9999-999999999999',
  'Premium HOODIES No.1', 'محصول پریمیوم دسته‌بندی hoodies شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-HOODIES-41', false, 0,
  '/images/category-hoodie.png', ARRAY['/images/category-hoodie.png'],
  false, NOW()
),
(
  '3c8361f3-23a5-4125-a199-b0c09203b978', 'hoodies-item-2', 'active', 'public', 'physical', 'a9999999-9999-9999-9999-999999999999',
  'Classic HOODIES No.2', 'محصول کلاسیک دسته‌بندی hoodies شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-HOODIES-42', false, 0,
  '/images/category-hoodie.png', ARRAY['/images/category-hoodie.png'],
  false, NOW()
),
(
  '8f988a46-90ee-409f-8dbd-6351d8e06c0f', 'hoodies-item-3', 'active', 'public', 'physical', 'a9999999-9999-9999-9999-999999999999',
  'Heritage HOODIES No.3', 'محصول میراث دسته‌بندی hoodies شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-HOODIES-43', false, 0,
  '/images/category-hoodie.png', ARRAY['/images/category-hoodie.png'],
  false, NOW()
),
(
  '794bd8a5-fc61-44fc-9046-fafb4d9b49bf', 'hoodies-item-4', 'active', 'public', 'physical', 'a9999999-9999-9999-9999-999999999999',
  'Modern HOODIES No.4', 'محصول مدرن دسته‌بندی hoodies شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-HOODIES-44', false, 0,
  '/images/category-hoodie.png', ARRAY['/images/category-hoodie.png'],
  false, NOW()
),
(
  'f33d1e5f-00d2-4e73-a6fb-3cdb0a23a2fe', 'hoodies-item-5', 'active', 'public', 'physical', 'a9999999-9999-9999-9999-999999999999',
  'Artisanal HOODIES No.5', 'محصول دست‌ساز دسته‌بندی hoodies شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-HOODIES-45', false, 0,
  '/images/category-hoodie.png', ARRAY['/images/category-hoodie.png'],
  false, NOW()
),
(
  '8920e2a3-fa70-454d-ab0d-875964260610', 'kids-clothing-item-1', 'active', 'public', 'physical', 'a0000000-0000-0000-0000-000000000000',
  'Premium KIDS CLOTHING No.1', 'محصول پریمیوم دسته‌بندی kids-clothing شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-KIDS-CLOTHING-46', false, 0,
  '/images/category-kids.png', ARRAY['/images/category-kids.png'],
  false, NOW()
),
(
  '74e328e5-3234-45c7-8f28-48cdf12ad698', 'kids-clothing-item-2', 'active', 'public', 'physical', 'a0000000-0000-0000-0000-000000000000',
  'Classic KIDS CLOTHING No.2', 'محصول کلاسیک دسته‌بندی kids-clothing شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-KIDS-CLOTHING-47', false, 0,
  '/images/category-kids.png', ARRAY['/images/category-kids.png'],
  false, NOW()
),
(
  '4bd959ee-4602-4f06-9940-2d061b4c4ba1', 'kids-clothing-item-3', 'active', 'public', 'physical', 'a0000000-0000-0000-0000-000000000000',
  'Heritage KIDS CLOTHING No.3', 'محصول میراث دسته‌بندی kids-clothing شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-KIDS-CLOTHING-48', false, 0,
  '/images/category-kids.png', ARRAY['/images/category-kids.png'],
  false, NOW()
),
(
  '3854599d-b5d0-462f-879c-0dab2bf3582f', 'kids-clothing-item-4', 'active', 'public', 'physical', 'a0000000-0000-0000-0000-000000000000',
  'Modern KIDS CLOTHING No.4', 'محصول مدرن دسته‌بندی kids-clothing شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-KIDS-CLOTHING-49', false, 0,
  '/images/category-kids.png', ARRAY['/images/category-kids.png'],
  false, NOW()
),
(
  '9b2e7eff-bcb3-4dbd-9596-d9283d1c8007', 'kids-clothing-item-5', 'active', 'public', 'physical', 'a0000000-0000-0000-0000-000000000000',
  'Artisanal KIDS CLOTHING No.5', 'محصول دست‌ساز دسته‌بندی kids-clothing شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-KIDS-CLOTHING-50', false, 0,
  '/images/category-kids.png', ARRAY['/images/category-kids.png'],
  false, NOW()
),
(
  '7b4fda3e-ceee-446f-887d-be727e0fd01a', 'stickers-item-1', 'active', 'public', 'physical', 'b1111111-1111-1111-1111-111111111111',
  'Premium STICKERS No.1', 'محصول پریمیوم دسته‌بندی stickers شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-STICKERS-51', false, 0,
  '/images/category-stickers.png', ARRAY['/images/category-stickers.png'],
  false, NOW()
),
(
  'df17881b-1c52-43bc-a614-9707ca82effc', 'stickers-item-2', 'active', 'public', 'physical', 'b1111111-1111-1111-1111-111111111111',
  'Classic STICKERS No.2', 'محصول کلاسیک دسته‌بندی stickers شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-STICKERS-52', false, 0,
  '/images/category-stickers.png', ARRAY['/images/category-stickers.png'],
  false, NOW()
),
(
  '006fc06b-09ea-4939-bd1e-363f224eccf5', 'stickers-item-3', 'active', 'public', 'physical', 'b1111111-1111-1111-1111-111111111111',
  'Heritage STICKERS No.3', 'محصول میراث دسته‌بندی stickers شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-STICKERS-53', false, 0,
  '/images/category-stickers.png', ARRAY['/images/category-stickers.png'],
  false, NOW()
),
(
  '2f1638db-b35a-4957-9deb-08fdff669356', 'stickers-item-4', 'active', 'public', 'physical', 'b1111111-1111-1111-1111-111111111111',
  'Modern STICKERS No.4', 'محصول مدرن دسته‌بندی stickers شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-STICKERS-54', false, 0,
  '/images/category-stickers.png', ARRAY['/images/category-stickers.png'],
  false, NOW()
),
(
  'e0571fa4-fe08-46e5-a65f-f40b41dbce32', 'stickers-item-5', 'active', 'public', 'physical', 'b1111111-1111-1111-1111-111111111111',
  'Artisanal STICKERS No.5', 'محصول دست‌ساز دسته‌بندی stickers شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-STICKERS-55', false, 0,
  '/images/category-stickers.png', ARRAY['/images/category-stickers.png'],
  false, NOW()
),
(
  'f1dcb37c-bc5e-4273-9536-9c9a27b0952b', 'phone-cases-item-1', 'active', 'public', 'physical', 'b2222222-2222-2222-2222-222222222222',
  'Premium PHONE CASES No.1', 'محصول پریمیوم دسته‌بندی phone-cases شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-PHONE-CASES-56', false, 0,
  '/images/category-phonecases.png', ARRAY['/images/category-phonecases.png'],
  false, NOW()
),
(
  'feb64ae0-6b0b-4604-9b32-e0bbe79690d3', 'phone-cases-item-2', 'active', 'public', 'physical', 'b2222222-2222-2222-2222-222222222222',
  'Classic PHONE CASES No.2', 'محصول کلاسیک دسته‌بندی phone-cases شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-PHONE-CASES-57', false, 0,
  '/images/category-phonecases.png', ARRAY['/images/category-phonecases.png'],
  false, NOW()
),
(
  'e507f661-0b02-4f3e-9431-dd92f27075ab', 'phone-cases-item-3', 'active', 'public', 'physical', 'b2222222-2222-2222-2222-222222222222',
  'Heritage PHONE CASES No.3', 'محصول میراث دسته‌بندی phone-cases شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-PHONE-CASES-58', false, 0,
  '/images/category-phonecases.png', ARRAY['/images/category-phonecases.png'],
  false, NOW()
),
(
  'f7231f76-8808-48bb-b47b-72d0fef9bb39', 'phone-cases-item-4', 'active', 'public', 'physical', 'b2222222-2222-2222-2222-222222222222',
  'Modern PHONE CASES No.4', 'محصول مدرن دسته‌بندی phone-cases شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-PHONE-CASES-59', false, 0,
  '/images/category-phonecases.png', ARRAY['/images/category-phonecases.png'],
  false, NOW()
),
(
  'a9fe477a-c295-49d2-bec6-d431dfcc711a', 'phone-cases-item-5', 'active', 'public', 'physical', 'b2222222-2222-2222-2222-222222222222',
  'Artisanal PHONE CASES No.5', 'محصول دست‌ساز دسته‌بندی phone-cases شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-PHONE-CASES-60', false, 0,
  '/images/category-phonecases.png', ARRAY['/images/category-phonecases.png'],
  false, NOW()
),
(
  'a852f85f-912c-4815-91c4-745e5539a46d', 'posters-item-1', 'active', 'public', 'physical', 'b3333333-3333-3333-3333-333333333333',
  'Premium POSTERS No.1', 'محصول پریمیوم دسته‌بندی posters شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-POSTERS-61', false, 0,
  '/images/category-posters.png', ARRAY['/images/category-posters.png'],
  false, NOW()
),
(
  '79b96e64-7a0a-4716-9e7b-b92a9a0a681b', 'posters-item-2', 'active', 'public', 'physical', 'b3333333-3333-3333-3333-333333333333',
  'Classic POSTERS No.2', 'محصول کلاسیک دسته‌بندی posters شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-POSTERS-62', false, 0,
  '/images/category-posters.png', ARRAY['/images/category-posters.png'],
  false, NOW()
),
(
  '3623d642-28ec-4e42-ac6d-247601d49577', 'posters-item-3', 'active', 'public', 'physical', 'b3333333-3333-3333-3333-333333333333',
  'Heritage POSTERS No.3', 'محصول میراث دسته‌بندی posters شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-POSTERS-63', false, 0,
  '/images/category-posters.png', ARRAY['/images/category-posters.png'],
  false, NOW()
),
(
  'ac154ec3-4641-49a1-b5f5-a02a377043ee', 'posters-item-4', 'active', 'public', 'physical', 'b3333333-3333-3333-3333-333333333333',
  'Modern POSTERS No.4', 'محصول مدرن دسته‌بندی posters شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-POSTERS-64', false, 0,
  '/images/category-posters.png', ARRAY['/images/category-posters.png'],
  false, NOW()
),
(
  '3cf3571d-161d-4c78-95f0-27b91b4112d6', 'posters-item-5', 'active', 'public', 'physical', 'b3333333-3333-3333-3333-333333333333',
  'Artisanal POSTERS No.5', 'محصول دست‌ساز دسته‌بندی posters شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-POSTERS-65', false, 0,
  '/images/category-posters.png', ARRAY['/images/category-posters.png'],
  false, NOW()
),
(
  'aeee5448-9472-4a1c-b712-07eb403493e5', 'candles-item-1', 'active', 'public', 'physical', 'b4444444-4444-4444-4444-444444444444',
  'Premium CANDLES No.1', 'محصول پریمیوم دسته‌بندی candles شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-CANDLES-66', false, 0,
  '/images/category-candles.png', ARRAY['/images/category-candles.png'],
  false, NOW()
),
(
  '531c6665-7b01-4608-941e-38c95cac6122', 'candles-item-2', 'active', 'public', 'physical', 'b4444444-4444-4444-4444-444444444444',
  'Classic CANDLES No.2', 'محصول کلاسیک دسته‌بندی candles شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-CANDLES-67', false, 0,
  '/images/category-candles.png', ARRAY['/images/category-candles.png'],
  false, NOW()
),
(
  '7ad58b9d-386f-4839-9bfe-ebaa7931af11', 'candles-item-3', 'active', 'public', 'physical', 'b4444444-4444-4444-4444-444444444444',
  'Heritage CANDLES No.3', 'محصول میراث دسته‌بندی candles شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-CANDLES-68', false, 0,
  '/images/category-candles.png', ARRAY['/images/category-candles.png'],
  false, NOW()
),
(
  '6649fb04-dc93-4e49-af99-ea08d06688d1', 'candles-item-4', 'active', 'public', 'physical', 'b4444444-4444-4444-4444-444444444444',
  'Modern CANDLES No.4', 'محصول مدرن دسته‌بندی candles شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-CANDLES-69', false, 0,
  '/images/category-candles.png', ARRAY['/images/category-candles.png'],
  false, NOW()
),
(
  '1ad8cc0a-48c9-4b29-94da-389bd0894932', 'candles-item-5', 'active', 'public', 'physical', 'b4444444-4444-4444-4444-444444444444',
  'Artisanal CANDLES No.5', 'محصول دست‌ساز دسته‌بندی candles شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-CANDLES-70', false, 0,
  '/images/category-candles.png', ARRAY['/images/category-candles.png'],
  false, NOW()
),
(
  'cec7f3bc-9430-407c-8293-d1caf4395847', 'bags-item-1', 'active', 'public', 'physical', 'b5555555-5555-5555-5555-555555555555',
  'Premium BAGS No.1', 'محصول پریمیوم دسته‌بندی bags شماره 1',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  39, 15.600000000000001, 'CAD', 'UT-BAGS-71', false, 0,
  '/images/category-bags.png', ARRAY['/images/category-bags.png'],
  false, NOW()
),
(
  'f35e5786-1730-4363-be2b-e69163ee6bf9', 'bags-item-2', 'active', 'public', 'physical', 'b5555555-5555-5555-5555-555555555555',
  'Classic BAGS No.2', 'محصول کلاسیک دسته‌بندی bags شماره 2',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  49, 19.6, 'CAD', 'UT-BAGS-72', false, 0,
  '/images/category-bags.png', ARRAY['/images/category-bags.png'],
  false, NOW()
),
(
  'e7c92774-3988-4b10-b26e-00db13c5578e', 'bags-item-3', 'active', 'public', 'physical', 'b5555555-5555-5555-5555-555555555555',
  'Heritage BAGS No.3', 'محصول میراث دسته‌بندی bags شماره 3',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  59, 23.6, 'CAD', 'UT-BAGS-73', false, 0,
  '/images/category-bags.png', ARRAY['/images/category-bags.png'],
  false, NOW()
),
(
  'b3755057-d746-4895-b160-5e2e22fe25a4', 'bags-item-4', 'active', 'public', 'physical', 'b5555555-5555-5555-5555-555555555555',
  'Modern BAGS No.4', 'محصول مدرن دسته‌بندی bags شماره 4',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  69, 27.6, 'CAD', 'UT-BAGS-74', false, 0,
  '/images/category-bags.png', ARRAY['/images/category-bags.png'],
  false, NOW()
),
(
  'a5b7794d-36fb-4e4f-b7f8-4e936122d421', 'bags-item-5', 'active', 'public', 'physical', 'b5555555-5555-5555-5555-555555555555',
  'Artisanal BAGS No.5', 'محصول دست‌ساز دسته‌بندی bags شماره 5',
  'Experience the luxury of ancient Persian identity with this exquisite piece.', 'شکوه هویت باستانی ایران را با این قطعه نفیس تجربه کنید.',
  'Carefully crafted and designed with the utmost attention to detail. This piece carries the essence of our heritage in a modern form.', 'با دقت و ظرافت بالا ساخته شده. این محصول عصاره‌ای از میراث ما در قالبی مدرن است.',
  'Inspired by the vast history of Persia, bringing thousands of years of art into everyday life.', 'الهام گرفته از تاریخ پهناور ایران، پیونددهنده هزاران سال هنر با زندگی روزمره.',
  79, 31.6, 'CAD', 'UT-BAGS-75', false, 0,
  '/images/category-bags.png', ARRAY['/images/category-bags.png'],
  false, NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_fa = EXCLUDED.name_fa,
  price = EXCLUDED.price;
\n-- New Iran Words Products\n
INSERT INTO public.products (id, slug, name_en, name_fa, description_en, description_fa, price, stock, collection_id, images, category)
VALUES (
  'p-words-iran-1',
  'iran-typography-t-shirt',
  'Iran (ایران) Typography T-Shirt',
  'تی‌شرت با تایپوگرافی ایران',
  'A minimalist, premium cotton t-shirt featuring the word ''ایران'' (Iran) in modern, elegant Persian typography. Celebrating the rich cultural heritage and pre-Islamic history of the land in a contemporary style.',
  'تی‌شرت نخی پریمیوم با تایپوگرافی مدرن و مینیمال کلمه «ایران». ادای احترامی به تاریخ و فرهنگ غنی ایران باستان با طراحی امروزی.',
  45,
  100,
  'col-words',
  ARRAY['/images/products/iran-typography-t-shirt.png']::text[],
  'clothing'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, slug, name_en, name_fa, description_en, description_fa, price, stock, collection_id, images, category)
VALUES (
  'p-words-iran-2',
  'iran-gold-necklace',
  'Iran (ایران) 18k Gold Necklace',
  'گردنبند طلای ۱۸ عیار ایران',
  'An exquisite 18k gold necklace where the word ''ایران'' is crafted in a geometric, pre-Islamic inspired modern twist. A subtle yet powerful statement of identity.',
  'گردنبند ظریف و زیبای طلای ۱۸ عیار که کلمه «ایران» با طراحی هندسی و الهام‌گرفته از هنر ایران باستان در آن نقش بسته است.',
  320,
  30,
  'col-words',
  ARRAY['/images/products/iran-gold-necklace.png']::text[],
  'jewelry'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, slug, name_en, name_fa, description_en, description_fa, price, stock, collection_id, images, category)
VALUES (
  'p-words-iran-3',
  'iran-canvas-tote-bag',
  'Iran (ایران) Minimalist Tote Bag',
  'کیف پارچه‌ای مینیمال ایران',
  'A heavy-duty canvas tote bag featuring the word ''ایران'' in bold, contemporary typography. Perfect for everyday use while carrying a piece of your roots.',
  'کیف پارچه‌ای مقاوم با تایپوگرافی مدرن و درشت «ایران». همراهی ایده‌آل برای استفاده روزمره و گرامیداشت ریشه‌ها.',
  35,
  150,
  'col-words',
  ARRAY['/images/products/iran-canvas-tote-bag.png']::text[],
  'accessory'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, slug, name_en, name_fa, description_en, description_fa, price, stock, collection_id, images, category)
VALUES (
  'p-words-iran-4',
  'iran-ceramic-mug',
  'Iran (ایران) Artisan Ceramic Mug',
  'ماگ سرامیکی دست‌ساز ایران',
  'A handcrafted ceramic mug featuring the word ''ایران'' in a beautifully debossed, subtle styling. Fired with earthy tones reminiscent of the Iranian plateau.',
  'ماگ سرامیکی دست‌ساز با حکاکی ظریف و زیبای کلمه «ایران». رنگ‌آمیزی شده با تناژهای خاکی با الهام از فلات ایران.',
  28,
  80,
  'col-words',
  ARRAY['/images/products/iran-ceramic-mug.png']::text[],
  'home'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, slug, name_en, name_fa, description_en, description_fa, price, stock, collection_id, images, category)
VALUES (
  'p-words-iran-5',
  'iran-neon-wall-art',
  'Iran (ایران) Neon LED Wall Art',
  'دیوارکوب نئونی ایران',
  'An aesthetic LED neon sign spelling ''ایران'' in an elegant, flowing script. A striking, modern decor piece that lights up any space with cultural pride.',
  'تابلوی نئون LED با طراحی تایپوگرافی روان و زیبای «ایران». قطعه‌ای مدرن برای دکوراسیون که به فضا جلوه‌ای از افتخار و اصالت می‌بخشد.',
  150,
  20,
  'col-words',
  ARRAY['/images/products/iran-neon-wall-art.png']::text[],
  'decor'
) ON CONFLICT (id) DO NOTHING;
