-- ============================================================================
-- Upside Tree — Schema Sync CORRECTION
--
-- WHY THIS EXISTS
-- 20260816000000_sync_live_schema.sql was supposed to create all 18 missing
-- tables verbatim from schema.sql. While assembling that file, several of
-- the "supporting" tables (media_library, product_variants,
-- product_attributes, product_tags, carts, cart_items, coupons,
-- shipping_zones, tax_rates, restock_notifications, media_assets,
-- navigation_menus, announcement_bars, redirects, custom_scripts) were
-- hand-typed from memory instead of copied verbatim from schema.sql, and
-- drifted from the intended schema on day one — e.g. cart_items got
-- `price_at_add` instead of the real `unit_price` + `product_snapshot`
-- columns, which is what src/app/api/cart/route.ts actually writes to.
-- That mismatch has been silently breaking cart persistence since the
-- first migration ran.
--
-- This migration was generated by extracting the CREATE TABLE statements
-- directly from schema.sql via script (not retyped), to remove any more
-- risk of transcription error.
--
-- SAFETY
-- All 18 tables were confirmed empty (0 rows) in production immediately
-- before writing this migration, so it safely DROPs and recreates them
-- verbatim from schema.sql rather than patching column-by-column — an
-- exact match with zero ambiguity. Nothing outside these 18 tables is
-- touched; products/collections/orders/order_items (which were correctly
-- generated the first time) are untouched here.
-- ============================================================================

BEGIN;

-- 1. DROP the 18 tables (reverse dependency order — safe, all empty)
DROP TABLE IF EXISTS public.custom_scripts CASCADE;
DROP TABLE IF EXISTS public.redirects CASCADE;
DROP TABLE IF EXISTS public.announcement_bars CASCADE;
DROP TABLE IF EXISTS public.navigation_menus CASCADE;
DROP TABLE IF EXISTS public.media_assets CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.restock_notifications CASCADE;
DROP TABLE IF EXISTS public.tax_rates CASCADE;
DROP TABLE IF EXISTS public.shipping_zones CASCADE;
DROP TABLE IF EXISTS public.coupons CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.carts CASCADE;
DROP TABLE IF EXISTS public.product_revisions CASCADE;
DROP TABLE IF EXISTS public.product_tag_relations CASCADE;
DROP TABLE IF EXISTS public.product_tags CASCADE;
DROP TABLE IF EXISTS public.product_attributes CASCADE;
DROP TABLE IF EXISTS public.product_variants CASCADE;
DROP TABLE IF EXISTS public.media_library CASCADE;

-- 2. RECREATE verbatim from schema.sql (forward dependency order)

CREATE TABLE public.media_library (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    filename VARCHAR NOT NULL,
    original_name VARCHAR NOT NULL,
    url TEXT NOT NULL,
    thumbnail_url TEXT,
    file_type VARCHAR CHECK (file_type IN ('image', 'video', 'document')),
    mime_type VARCHAR,
    size_bytes INTEGER,
    width INTEGER,
    height INTEGER,
    alt_text_en VARCHAR,
    alt_text_fa VARCHAR,
    caption_en VARCHAR,
    caption_fa VARCHAR,
    folder VARCHAR DEFAULT 'uncategorized',
    tags TEXT[] DEFAULT '{}',
    used_in JSONB DEFAULT '[]'::jsonb,
    uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.product_variants (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    sku VARCHAR UNIQUE,
    name_en VARCHAR NOT NULL,
    name_fa VARCHAR,
    attributes JSONB DEFAULT '{}'::jsonb,
    price DECIMAL(10,2),
    sale_price DECIMAL(10,2),
    cost_price DECIMAL(10,2),
    stock_quantity INTEGER,
    stock_status VARCHAR DEFAULT 'in_stock' CHECK (stock_status IN ('in_stock', 'out_of_stock', 'on_backorder')),
    weight_grams INTEGER,
    image_url TEXT,
    printful_variant_id VARCHAR,
    is_default BOOLEAN DEFAULT false,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.product_attributes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name_en VARCHAR NOT NULL,
    name_fa VARCHAR NOT NULL,
    slug VARCHAR UNIQUE NOT NULL,
    type VARCHAR CHECK (type IN ('select', 'color', 'text', 'number')),
    values JSONB DEFAULT '[]'::jsonb,
    is_visible BOOLEAN DEFAULT true,
    is_variation BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.product_tags (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name_en VARCHAR UNIQUE NOT NULL,
    name_fa VARCHAR,
    slug VARCHAR UNIQUE NOT NULL,
    count INTEGER DEFAULT 0
);

CREATE TABLE public.product_tag_relations (
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    tag_id UUID REFERENCES public.product_tags(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (product_id, tag_id)
);

CREATE TABLE public.product_revisions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    revision_data JSONB NOT NULL,
    saved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    saved_at TIMESTAMPTZ DEFAULT now(),
    note VARCHAR
);

CREATE TABLE public.carts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id UUID REFERENCES public.customer_profiles(id) ON DELETE SET NULL,
    session_id UUID,
    status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'merged', 'abandoned', 'converted')),
    currency VARCHAR DEFAULT 'CAD',
    coupon_code VARCHAR,
    discount_amount DECIMAL(10,2) DEFAULT 0,
    gift_wrap BOOLEAN DEFAULT false,
    gift_message TEXT, -- max 150 chars
    notes TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    cart_id UUID REFERENCES public.carts(id) ON DELETE CASCADE NOT NULL,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    variant_id UUID REFERENCES public.product_variants(id) ON DELETE SET NULL,
    quantity INTEGER DEFAULT 1,
    unit_price DECIMAL(10,2) NOT NULL,
    sale_price DECIMAL(10,2),
    product_snapshot JSONB NOT NULL,
    added_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.coupons (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    code VARCHAR UNIQUE NOT NULL,
    type VARCHAR NOT NULL CHECK (type IN ('percentage', 'fixed', 'free_shipping', 'buy_x_get_y')),
    value DECIMAL(10,2) NOT NULL,
    minimum_order DECIMAL(10,2),
    maximum_discount DECIMAL(10,2),
    collection_scope UUID[],
    product_scope UUID[],
    usage_limit INTEGER,
    usage_per_customer INTEGER,
    usage_count INTEGER DEFAULT 0,
    customer_scope UUID[],
    starts_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    active BOOLEAN DEFAULT true,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.shipping_zones (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR NOT NULL,
    countries TEXT[] NOT NULL,
    rates JSONB NOT NULL,
    active BOOLEAN DEFAULT true
);

CREATE TABLE public.tax_rates (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    country VARCHAR DEFAULT 'CA',
    province VARCHAR,
    tax_name VARCHAR NOT NULL,
    rate DECIMAL(5,4) NOT NULL,
    compound BOOLEAN DEFAULT false,
    active BOOLEAN DEFAULT true
);

CREATE TABLE public.restock_notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    variant_id UUID REFERENCES public.product_variants(id) ON DELETE CASCADE,
    email VARCHAR NOT NULL,
    customer_id UUID REFERENCES public.customer_profiles(id) ON DELETE SET NULL,
    notified BOOLEAN DEFAULT false,
    notified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    namespace VARCHAR NOT NULL CHECK (namespace IN ('general', 'branding', 'seo', 'payments', 'shipping', 'email', 'tax', 'integrations', 'security', 'advanced')),
    key VARCHAR NOT NULL,
    value TEXT, -- JSON-serialized for complex values
    value_type VARCHAR NOT NULL CHECK (value_type IN ('string', 'number', 'boolean', 'json', 'secret', 'file_url')),
    label_en VARCHAR NOT NULL,
    label_fa VARCHAR,
    description VARCHAR,
    is_secret BOOLEAN DEFAULT false,
    is_public BOOLEAN DEFAULT false,
    updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (namespace, key)
);

CREATE TABLE public.media_assets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    asset_type VARCHAR NOT NULL,
    url TEXT NOT NULL,
    width INTEGER,
    height INTEGER,
    file_size INTEGER,
    mime_type VARCHAR,
    alt_en VARCHAR,
    alt_fa VARCHAR,
    uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    uploaded_at TIMESTAMPTZ DEFAULT now(),
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.navigation_menus (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    location VARCHAR NOT NULL UNIQUE CHECK (location IN ('header_main', 'header_secondary', 'footer_collections', 'footer_company', 'footer_legal', 'mobile_bottom', 'account_sidebar')),
    label_en VARCHAR NOT NULL,
    label_fa VARCHAR NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.announcement_bars (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    text_en VARCHAR NOT NULL,
    text_fa VARCHAR NOT NULL,
    link_url TEXT,
    link_text_en VARCHAR,
    link_text_fa VARCHAR,
    bg_color VARCHAR DEFAULT '#1D4E89',
    text_color VARCHAR DEFAULT '#F4EFE3',
    is_active BOOLEAN DEFAULT false,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    is_dismissible BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.redirects (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    from_path VARCHAR UNIQUE NOT NULL,
    to_path VARCHAR NOT NULL,
    type INTEGER NOT NULL CHECK (type IN (301, 302)),
    hits INTEGER DEFAULT 0,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.custom_scripts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR NOT NULL,
    location VARCHAR NOT NULL CHECK (location IN ('head', 'body_start', 'body_end')),
    script TEXT NOT NULL,
    is_active BOOLEAN DEFAULT false,
    pages TEXT[] DEFAULT ARRAY['all'],
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. RE-ENABLE RLS
ALTER TABLE public.media_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_attributes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_tag_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restock_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.navigation_menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcement_bars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.redirects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_scripts ENABLE ROW LEVEL SECURITY;

-- 4. RE-CREATE POLICIES
DROP POLICY IF EXISTS "Public variants viewable by everyone" ON public.product_variants;
CREATE POLICY "Public variants viewable by everyone" ON public.product_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public attributes viewable by everyone" ON public.product_attributes;
CREATE POLICY "Public attributes viewable by everyone" ON public.product_attributes FOR SELECT USING (is_visible = true);

DROP POLICY IF EXISTS "Users can manage their carts." ON public.carts;
CREATE POLICY "Users can manage their carts." ON public.carts FOR ALL USING (auth.uid() = customer_id);

DROP POLICY IF EXISTS "Users can manage their cart items." ON public.cart_items;
CREATE POLICY "Users can manage their cart items." ON public.cart_items FOR ALL USING (cart_id IN (SELECT id FROM public.carts WHERE customer_id = auth.uid()));

DROP POLICY IF EXISTS "Public shipping zones are viewable by everyone" ON public.shipping_zones;
CREATE POLICY "Public shipping zones are viewable by everyone" ON public.shipping_zones FOR SELECT USING (active = true);

DROP POLICY IF EXISTS "Public tax rates are viewable by everyone" ON public.tax_rates;
CREATE POLICY "Public tax rates are viewable by everyone" ON public.tax_rates FOR SELECT USING (active = true);

DROP POLICY IF EXISTS "Admins have full access to media_library" ON public.media_library;
CREATE POLICY "Admins have full access to media_library" ON public.media_library FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to product_variants" ON public.product_variants;
CREATE POLICY "Admins have full access to product_variants" ON public.product_variants FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to product_attributes" ON public.product_attributes;
CREATE POLICY "Admins have full access to product_attributes" ON public.product_attributes FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to product_tags" ON public.product_tags;
CREATE POLICY "Admins have full access to product_tags" ON public.product_tags FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to product_tag_relations" ON public.product_tag_relations;
CREATE POLICY "Admins have full access to product_tag_relations" ON public.product_tag_relations FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to product_revisions" ON public.product_revisions;
CREATE POLICY "Admins have full access to product_revisions" ON public.product_revisions FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to carts" ON public.carts;
CREATE POLICY "Admins have full access to carts" ON public.carts FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to cart_items" ON public.cart_items;
CREATE POLICY "Admins have full access to cart_items" ON public.cart_items FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to coupons" ON public.coupons;
CREATE POLICY "Admins have full access to coupons" ON public.coupons FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to shipping_zones" ON public.shipping_zones;
CREATE POLICY "Admins have full access to shipping_zones" ON public.shipping_zones FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to tax_rates" ON public.tax_rates;
CREATE POLICY "Admins have full access to tax_rates" ON public.tax_rates FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins have full access to restock_notifications" ON public.restock_notifications;
CREATE POLICY "Admins have full access to restock_notifications" ON public.restock_notifications FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can manage settings" ON public.settings;
CREATE POLICY "Admins can manage settings" ON public.settings FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Public settings are viewable by everyone" ON public.settings;
CREATE POLICY "Public settings are viewable by everyone" ON public.settings FOR SELECT USING (is_public = true);

DROP POLICY IF EXISTS "Admins can manage media assets" ON public.media_assets;
CREATE POLICY "Admins can manage media assets" ON public.media_assets FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Media assets are viewable by everyone" ON public.media_assets;
CREATE POLICY "Media assets are viewable by everyone" ON public.media_assets FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage navigation menus" ON public.navigation_menus;
CREATE POLICY "Admins can manage navigation menus" ON public.navigation_menus FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Navigation menus are viewable by everyone" ON public.navigation_menus;
CREATE POLICY "Navigation menus are viewable by everyone" ON public.navigation_menus FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage announcement bars" ON public.announcement_bars;
CREATE POLICY "Admins can manage announcement bars" ON public.announcement_bars FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Announcement bars are viewable by everyone" ON public.announcement_bars;
CREATE POLICY "Announcement bars are viewable by everyone" ON public.announcement_bars FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage redirects" ON public.redirects;
CREATE POLICY "Admins can manage redirects" ON public.redirects FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Redirects are viewable by everyone" ON public.redirects;
CREATE POLICY "Redirects are viewable by everyone" ON public.redirects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage custom scripts" ON public.custom_scripts;
CREATE POLICY "Admins can manage custom scripts" ON public.custom_scripts FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Custom scripts are viewable by everyone" ON public.custom_scripts;
CREATE POLICY "Custom scripts are viewable by everyone" ON public.custom_scripts FOR SELECT USING (true);

-- 5. RE-CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_settings_namespace ON public.settings(namespace);
CREATE INDEX IF NOT EXISTS idx_settings_is_public ON public.settings(is_public);

COMMIT;
